Add `MitEx.run_basic`
CQCL/Qermit pull request #48
Opened 2022-04-20 10:37 UTC by sjdilkes

`MitEx.run` requires `List[ObservableExperiment]` as an argument which, while necessary for supporting graphs for combined error mitigation schemes, is potentially confusing to new users. `MitEx.run_basic` requires `List[Tuple[CircuitShots, QubitPauliOperator]]` as an argument, two types that are more familiar to users coming from other `pytket` use.

On call the method reworks the given arguments into a `List[ObservableExperiment]` object which is then passed to run.

2022-04-20 18:24 UTC, daniel-mills-cqc requested changes
Nice, looks good. How would this not work for combining error mitigation methods. Do we want to mention that?

2022-04-21 08:18 UTC, sjdilkes commented
> Nice, looks good. How would this not work for combining error mitigation methods. Do we want to mention that?

Sorry I wasn't clear, I meant that the range of arguments for `run_basic` are not descriptive enough to replace `run` in general with the main problem being combining methods. When we combine methods at some point the "internal" method will be used as a callable, which will execute its internal `run` method. The range of things we can expect a mitigation method (or general experimental method) to do is wider than that provided by `List[Tuple[CircuitShots, QubitPauliOperator]]`.

As an example: ObservableExperiment/ObservableTracker exist to map between the components of some operator and their corresponding measurement circuits, which is necessary because if we want to run something like measurement reduction then a single measurement circuit can produce results for multiple operators. The arguments provided by `run_basic` are not descriptive enough to cover this sufficiently.

Similarly (as it is not commonly used) I've removed `SymbolsDict` from the `run_basic` arguments, but running these style experiments with symbolics is common (outside Qermit).

You can still create a `MitEx` object that defines some combined error mitigation scheme and then execute that object using the `run_basic` method, it will just pass data on internally with `run`, so I think we don't need a comment here.

2022-04-21 10:13 UTC, daniel-mills-cqc commented
Ah, okay. Gottcha. Will you add this to the documentation?

2022-04-21 12:01 UTC, sjdilkes commented
> Ah, okay. Gottcha. Will you add this to the documentation?

I've added `run_basic` to the autodocs downstream

2022-04-21 13:25 UTC, merged